
name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build
        run: ./gradlew clean build --stacktrace
      - name: Instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck --stacktrace
