name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        include:
          - api-level: 15
            compose: false
            java-version: 1.8
          - api-level: 16
            compose: false
            java-version: 1.8
          - api-level: 17
            compose: false
            java-version: 1.8
          # TODO: Investigate flaky SecurityException during tests on API 18
          - api-level: 19
            compose: false
            java-version: 1.8
          - api-level: 21
            compose: true
            java-version: 11
          - api-level: 22
            compose: true
            java-version: 11
          - api-level: 23
            compose: true
            java-version: 11
          - api-level: 24
            compose: true
            java-version: 11
          - api-level: 25
            compose: true
            java-version: 11
          - api-level: 26
            compose: true
            java-version: 11
          - api-level: 27
            compose: true
            java-version: 11
          - api-level: 28
            compose: true
            java-version: 11
          - api-level: 29
            compose: true
            java-version: 11

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Install JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Build
        run: ./gradlew clean build -PcomposeEnabled=${{ matrix.compose }} --stacktrace
      - name: Report Detekt results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ github.workspace }}/build/detekt/sarif
          checkout_path: ${{ github.workspace }}
      - name: Instrumented tests
        uses: reactivecircus/android-emulator-runner@v2.14.3
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck -PcomposeEnabled=${{ matrix.compose }} --stacktrace
      - name: Publish test results
        uses: mikepenz/action-junit-report@v1.2.1
        if: success() || failure()
        with:
          check_name: Android test report for API ${{ matrix.api-level }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/build/outputs/androidTest-results/connected/flavors/debugAndroidTest/TEST-*.xml"

  scan_for_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          # Allows Gitleaks to scan the commit history of a whole PR:
          fetch-depth: '0'
      - name: Fetch Gitleaks rules
        uses: wei/wget@v1
        with:
          args: -O .rules.toml https://raw.githubusercontent.com/fnxpt/gitleaks-action/rules/.rules.toml
      - name: Gitleaks
        uses: zricethezav/gitleaks-action@v1.3.0
        with:
          config-path: .rules.toml
