name: CI

on:
  push:
    branches: main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build
        run: ./gradlew clean build --stacktrace
      - name: Instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck --stacktrace
      - name: Publish test results
        uses: mikepenz/action-junit-report@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: |
            "**/build/test-results/testDebugUnitTest/TEST-*.xml"
            "**/build/test-results/test/TEST-*.xml"
            "**/build/outputs/androidTest-results/connected/flavors/debugAndroidTest/TEST-*.xml"
