name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [ 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29 ]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Install JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: ./gradlew clean build -PciApiLevel=${{ matrix.api-level }} --stacktrace
      - name: Report Detekt results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ github.workspace }}/build/detekt/sarif
          checkout_path: ${{ github.workspace }}
      - name: Instrumented tests
        uses: reactivecircus/android-emulator-runner@v2.19.1
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck -PciApiLevel=${{ matrix.api-level }} --stacktrace
      - name: Publish test results
        uses: mikepenz/action-junit-report@v1.2.1
        if: success() || failure()
        with:
          check_name: Android test report for API ${{ matrix.api-level }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/build/outputs/androidTest-results/connected/**/TEST-*.xml"

  scan_for_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          # Allows Gitleaks to scan the commit history of a whole PR:
          fetch-depth: '0'
      - name: Fetch Gitleaks rules
        uses: wei/wget@v1
        with:
          args: -O .rules.toml https://raw.githubusercontent.com/fnxpt/gitleaks-action/rules/.rules.toml
      - name: Gitleaks
        uses: zricethezav/gitleaks-action@v1.3.0
        with:
          config-path: .rules.toml
