name: Publish docs to GitHub Pages

on:
  release:
    types: [published]

jobs:
  deploy-website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Prepare MkDocs
        run: .github/workflows/prepare_mkdocs.sh

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.21
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
