name: Release

on:
  push:
    branches: [ main, drew/pr-based-release ]
    tags: [ '*' ]

jobs:
  prepare:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.value }}

    steps:
      - name: Parse release version
        id: version
        uses: madhead/read-java-properties
        with:
          file: gradle.properties
          property: libraryVersion

  release:
    needs: prepare
    # Only proceed for tagged releases and snapshots:
    if: startsWith(github.ref, 'refs/tags/') || endsWith(needs.prepare.outputs.version, '-SNAPSHOT')
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Assemble for release
        run: ./gradlew clean assembleRelease --stacktrace
      - name: Publish
        env:
          ORG_GRADLE_PROJECT_backbaseOssSonatypeUsername: ${{ secrets.ORG_GRADLE_PROJECT_backbaseOssSonatypeUsername }}
          ORG_GRADLE_PROJECT_backbaseOssSonatypePassword: ${{ secrets.ORG_GRADLE_PROJECT_backbaseOssSonatypePassword }}
          ORG_GRADLE_PROJECT_backbaseOssGpgKey: ${{ secrets.ORG_GRADLE_PROJECT_backbaseOssGpgKey }}
          ORG_GRADLE_PROJECT_backbaseOssGpgPassword: ${{ secrets.ORG_GRADLE_PROJECT_backbaseOssGpgPassword }}
        run: ./gradlew publishReleasePublicationToMavenCentralRepository --stacktrace

  prepare-next-development-version:
    needs: release
    runs-on: ubuntu-latest
    # Only proceed for tagged releases:
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BACKBASE_BOT_TOKEN }}
      - name: Bump to next development version
        run: ./gradlew bumpToNextDevelopmentVersion
      - name: Push version to main
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Prepare next development version
          branch: main
          file_pattern: gradle.properties
          commit_author: GitHub Actions <actions@github.com>
