name: Find secrets

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: wget
      uses: wei/wget@v1
      with:
        args: -O .rules.toml https://raw.githubusercontent.com/fnxpt/gitleaks-action/rules/.rules.toml
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
      with:
        config-path: .rules.toml
